Complete Database Scripts
Dev-incubator/DIMS-Core.Double-3 pull request #1
Opened 2021-05-03 18:49 UTC by UNDogMan

2021-05-03 20:19 UTC, PushMeNow requested changes
Hi dude!
I left some comments. Let me know if any questions

2021-05-03 20:19 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteTask.sql
> +	DELETE [Tasks] WHERE TaskId = @TaskId;
I forgot <code>FROM</code>

2021-05-03 20:19 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskTracks.sql
> +	FOREIGN KEY (UserTaskId) REFERENCES UserTasks(UserTaskId)
Write name for your FK and on delete/update actions

2021-05-04 07:15 UTC, UNDogMan commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteTask.sql
> +	DELETE [Tasks] WHERE TaskId = @TaskId;
Why we need `FROM` here?

2021-05-05 18:05 UTC, PushMeNow approved these changes
Approve

2021-05-05 18:05 UTC, merged